# Generated by Django 5.0.7 on 2024-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название магазина'),
        ),
    ]
