# Generated by Django 5.0.7 on 2024-07-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
