# Generated by Django 5.0.7 on 2024-07-19 00:30

import Base.servises
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=Base.servises.get_upload_product_path, verbose_name='Фото'),
        ),
    ]
